version: '3.7'
services:

  zookeeper-test:
    image: jplock/zookeeper:3.4.6
    container_name: zookeeper-test
    ports:
      - "2181:2181"

  kafka-test:
    image: wurstmeister/kafka:2.13-2.6.0
    container_name: kafka-test
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-test:2181
      KAFKA_CREATE_TOPICS: "test-topic:1:1"
